language: 
  - c
  - node_js
node_js:
  - "0.10"
before_script:
  - git fetch --unshallow
script:
  - ./tools/tarball-bootstrap -a && make && make test
  - sudo make install
  - make js && make test.js
