language:
  - c
  - node_js
node_js:
  - "0.10"
install:
  - npm install performance-now
before_script:
  - git fetch --unshallow
script:
  - ./tools/tarball-bootstrap -a && (make test || ( cat tests/test.log ; exit 1))
  - ([ -e ./minigrace ] && ( make test.js || ( cat js/tests/test.log ; exit 1 )))
sudo: false
