language:
  - c
compiler:
  - clang
install:
  - nvm install 4.0.0
before_script:
  - git fetch --unshallow
script:
  - make test || ( cat tests/test.log ; exit 1)
  - ([ -e ./minigrace ] && ( make test.js || ( cat js/tests/test.js.log ; exit 1 )))
  - ([ -e ./minigrace ] && ( make test.js.js || ( cat js/tests/test.js.log ; exit 1 )))
  - make install
sudo: false
