language:
  - c
  - node_js
node_js:
  - "0.10"
install:
  - npm install performance-now
before_script:
  - git fetch --unshallow
script:
  - ./tools/tarball-bootstrap -a && make && make test
  - make js && make test.js
